CXX = clang++

all: compile run

compile:
	$(CXX) test_hits.cpp -o test.out

run:
	./test.out files_test/test1.txt files_test/answ_test1.txt files_test/test2.txt files_test/answ_test2.txt files_test/test3.txt files_test/answ_test3.txt files_test/test4.txt files_test/answ_test4.txt files_test/test5.txt files_test/answ_test5.txt files_test/test6.txt files_test/answ_test6.txt files_test/test7.txt files_test/answ_test7.txt files_test/test8.txt files_test/answ_test8.txt 
