all: compile run

compile:
	clang++ test_compl.cpp -o test.out

run:
	./test.out files_test/bigtest1.txt files_test/bigtest2.txt files_test/bigtest3.txt files_test/bigtest4.txt files_test/bigtest5.txt files_test/bigtest6.txt files_test/bigtest7.txt files_test/bigtest8.txt 