all: compile run

compile:
	clang++ test_compl.cpp -o test.out

run:
	./test.out files_test/test1.txt files_test/test2.txt files_test/test3.txt files_test/test4.txt files_test/test5.txt files_test/test6.txt files_test/test7.txt files_test/test8.txt 