#!/usr/bin/env bash

while getopts b: run_file
do
    case ${run_file} in 
        b) belady=${OPTARG};;
    esac
done

for i in $(seq 3 1 $#)
do
    ./$belady <$3 >'out'
    hits_act=$(< 'out')
    path=$(dirname "$3")/
    name=$(basename "$3")
    answ_name=answ_$name
    hits_test=$(< $"${path}${answ_name}")
    if [ "$hits_act" == "$hits_test" ]
    then
        echo "$((i -2)): Succes"
    else
        echo "$((i -2)): Error: hits in test $hits_test but tested exe print $hits_act"
    fi
    rm out
    shift
done